### ISSUE TITLE
Todo: Test Linux support

### ISSUE THREAD

**Issue by jogleasonjr** [jogleasonjr/electron-react-webpack-quick-start#5]
I would expect Linux to closely match the OSX build and run instructions, but it has yet to be tested.

**Comment by pfulop** [comment]
![screenshot from 2016-02-28 11-34-35](https://cloud.githubusercontent.com/assets/3984319/13378728/76a6e1ea-de0f-11e5-9eab-0c4edede6720.png)

tried on Linux 4.4.1-2-ARCH  and it works.

**Comment by jogleasonjr** [comment]
Thank you very much for testing! Glad to see it works! What's the concole error? I'g guessing something to do with Webpack hot reload.

**Comment by pfulop** [comment]
Actually no, It's a warning about markup.

> Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
>  (client) <b data-reactid=".0
>  (server) <b data-reactid=".0warning @ warning.js:45

**Comment by jogleasonjr** [comment]
Thanks, @pfulop, I will look into this.
