### ISSUE TITLE
Debugging from VSCode

### ISSUE THREAD

**Issue by MikePelton** [jogleasonjr/electron-react-webpack-quick-start#6]
Hi - was able to "start without debugging" with the vanilla project but not able to debug (VSCode, Windows 10) - kept seeing:
 "Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED....".  followed by a random port number.
This was fixed by adding 'protocol: "legacy"' to the Windows configuration in launch.json based on a suggestion from a www search - I have no idea why it made a difference!!

**Comment by jogleasonjr** [comment]
Thanks @MikePelton for letting me know the problem and solution. Fixed in f3ec4dd. More info about the debugger split [here](https://code.visualstudio.com/updates/v1_10#_node-debugging). Cheers!
